### ISSUE TITLE
IndefiniteSubject?

### ISSUE THREAD

**Issue by jverkoey** [material-motion/indefinite-observable-swift#1]
We need to identify when and how we might use an [IndefiniteSubject](http://reactivex.io/rxjs/manual/overview.html#subject).

One idea is for spring simulations, where a single spring simulation would drive all observers. If we use an Observable then we'd create a brand new spring simulation for each subscription chain.

```swift
/**
 An IndefiniteSubject is a special type of IndefiniteObservable that allows values to be multicasted
 to many Observers.

 IndefiniteObservables are unicast (each subscribed Observer owns an independent execution of
 the Observable). IndefiniteSubjects are multicast.

 Use IndefiniteSubject when you want to reuse the same delegates for each observer, such as an
 animation or gestural interaction.
 */
class IndefiniteSubject<T>: IndefiniteObservable<T>, Observer, Subscription {
  typealias Value = T

  override func subscribe(next: @escaping (T) -> Void) -> Subscription {
    let observer = AnyObserver<T>(next)
    observers.append(observer)

    if observers.count == 1 {
      // Keeping a strong reference to self would cause a retain cycle due to the subscription's
      // reference in the SimpleSubscription below, so we use a [weak self].
      subscription = super.subscribe { [weak self] in
        self?.next($0)
      }
    }

    return SimpleSubscription {
      if let index = self.observers.index(where: { $0 === observer }) {
        self.observers.remove(at: index)

        if self.observers.count == 0 {
          self.subscription?.unsubscribe()
        }
      }
    }
  }

  func next(_ value: T) {
    for observer in observers {
      observer.next(value)
    }
  }

  public func unsubscribe() {
    observers.removeAll()
  }

  private var observers: [AnyObserver<T>] = []
  private var subscription: Subscription?
}
```

**Comment by appsforartists** [comment]
_meta_: how is there no vinyl emoji?

**Comment by appsforartists** [comment]
I see the use of memoizing stream output, but this should be addressed in a different repo, or perhaps a thread in the Google Group.

Indefinite Observables reject features that can be implemented downstream.  😄

**Comment by jverkoey** [comment]
![vinyl-record-1-1024x768](https://cloud.githubusercontent.com/assets/45670/20862324/498a5628-b95c-11e6-8978-48e9b01779aa.png)

**Comment by appsforartists** [comment]
If you need a really simple one (like I made in JS), I'm happy to reopen this.  I just wanted to help keep us from scope-creeping in this repo, since `memoize` can be implemented as an operator.

**Comment by jverkoey** [comment]
I think we'll find it to be valuable for observable properties, so re-opening seems ok with me.

**Comment by jverkoey** [comment]
Closing in interest of keeping this repo focused on IndefiniteObservable.
