### ISSUE TITLE
Check that subscribers always return functions

### ISSUE THREAD

**Issue by appsforartists** [material-motion/indefinite-observable-swift#2]
Looks like you had subscribers returning Subscriptions at one point, and some docs/imp might still be that way:

https://github.com/material-motion/indefinite-observable-swift/blob/develop/src/IndefiniteObservable.swift#L44-L46

So do a sanity check through your code/docs/examples and make sure they consistently return functions.  =)

**Comment by jverkoey** [comment]
Typo resolved in 4f3b48a12f1e2a57d1b251db0c6a8a46f58e5e41.
